/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package database;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;



public class GlavnaForma extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GlavnaForma.class.getName());

    
    public void loadDrzave() {

    try {

        Connection conn = DBConnection.connect();

        String sql = "SELECT * FROM drzava";

        PreparedStatement ps = conn.prepareStatement(sql);

        ResultSet rs = ps.executeQuery();

        cmbDrzava.removeAllItems();


        while(rs.next()) {

            cmbDrzava.addItem(
                rs.getInt("DrzavaID") + " - " +
                rs.getString("Naziv")
            );
        }

    } catch(Exception e) {
        e.printStackTrace();
    }
}
    
    public GlavnaForma() {
        initComponents();
        loadDrzave();
        
    Connection conn = DBConnection.connect();
    System.out.println(conn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cmbDrzava = new javax.swing.JComboBox<>();
        cmbGrad = new javax.swing.JComboBox<>();
        cmbKlub = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnIzlaz = new javax.swing.JButton();
        PodaciKluba = new javax.swing.JLabel();
        lblSlika = new javax.swing.JLabel();
        lblStadion = new javax.swing.JLabel();
        lblSajt = new javax.swing.JLabel();
        lblGrad = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRezultati = new javax.swing.JTable();
        btnPrikazi = new javax.swing.JButton();
        btnIzlaz2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        dcDatum = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbDrzava.addActionListener(this::cmbDrzavaActionPerformed);

        cmbGrad.addActionListener(this::cmbGradActionPerformed);

        cmbKlub.addActionListener(this::cmbKlubActionPerformed);

        jLabel1.setText("Drzava");

        jLabel2.setText("Grad");

        jLabel3.setText("Klub");

        btnReset.setText("Reset pretrage");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnIzlaz.setText("Izadji");
        btnIzlaz.addActionListener(this::btnIzlazActionPerformed);

        PodaciKluba.setText("Podaci o klub:");

        jLabel4.setText("Logo:");

        jLabel5.setText("Grad:");

        jLabel6.setText("Sajt:");

        jLabel7.setText("Stadion:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PodaciKluba)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblSlika, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(30, 30, 30))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSajt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblStadion, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(cmbDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(cmbGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(cmbKlub, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnIzlaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbKlub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PodaciKluba)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 221, Short.MAX_VALUE)
                                .addComponent(btnIzlaz, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSajt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblStadion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSlika, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Podaci o klubovima", jPanel1);

        tblRezultati.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Stadion", "Domaca ekipa", "Golovi domacina", "Golovi gostiju", "Gostujuca ekipa"
            }
        ));
        jScrollPane1.setViewportView(tblRezultati);

        btnPrikazi.setText("Prikazi");
        btnPrikazi.addActionListener(this::btnPrikaziActionPerformed);

        btnIzlaz2.setText("Izadji");
        btnIzlaz2.addActionListener(this::btnIzlaz2ActionPerformed);

        jLabel8.setText("Datum utakmice");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(dcDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addGap(53, 53, 53)
                        .addComponent(btnPrikazi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzlaz2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPrikazi, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addComponent(btnIzlaz2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dcDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pregled rezultata", jPanel3);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("UPUTSTVO\n\nAplikacija služi za pregled fudbalskih klubova i utakmica.\n\n1. KLUBOVI\nIzabere se država, grad i klub.\nPrikazuju se logo, stadion, grad i sajt kluba.\n\n2. UTAKMICE\nIzabere se datum i klikne \"Prikaži\".\nU tabeli se prikazuju utakmice za taj dan (stadion, timovi, rezultat).\n\n3. OPCIJE\nReset briše izbor, Izlaz zatvara aplikaciju.\n\n");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Uputstvo", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGradActionPerformed
    if(cmbGrad.getSelectedIndex() == -1) return;

    try {

        String selected = cmbGrad.getSelectedItem().toString();
        int gradID = Integer.parseInt(selected.split(" - ")[0]);

        if(gradID == 0) {
           
    cmbKlub.removeAllItems();

    lblGrad.setText("");
    lblStadion.setText("");
    lblSajt.setText("");

    lblSlika.setIcon(null);

    return;
        }

        Connection conn = DBConnection.connect();

        String sql =
        "SELECT klub.NazivKluba " +
        "FROM klub " +
        "INNER JOIN stadion ON klub.StadionID = stadion.StadionID " +
        "WHERE stadion.GradID = ?";

        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, gradID);

        ResultSet rs = ps.executeQuery();

        cmbKlub.removeAllItems();

        while(rs.next()) {
            cmbKlub.addItem(rs.getString("NazivKluba"));
        }

    } catch(Exception e) {
        System.out.println(e);
    }
    }//GEN-LAST:event_cmbGradActionPerformed

    private void cmbDrzavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDrzavaActionPerformed

    if(cmbDrzava.getSelectedIndex() == -1) return;

    try {

        String selected = cmbDrzava.getSelectedItem().toString();
        int drzavaID = Integer.parseInt(selected.split(" - ")[0]);

        if(drzavaID == 0) {
               cmbGrad.removeAllItems();
    cmbKlub.removeAllItems();

    lblGrad.setText("");
    lblStadion.setText("");
    lblSajt.setText("");

    lblSlika.setIcon(null);

    return;
        }

        Connection conn = DBConnection.connect();

        String sql = "SELECT * FROM grad WHERE DrzavaID = ?";

        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, drzavaID);

        ResultSet rs = ps.executeQuery();

        cmbGrad.removeAllItems();

        cmbGrad.addItem("0 - Svi gradovi");

        while(rs.next()) {

            cmbGrad.addItem(
                rs.getInt("GradID")
                + " - " +
                rs.getString("Grad")
            );
        }

        cmbKlub.removeAllItems();

    } catch(Exception e) {
        System.out.println(e);
    }
    }//GEN-LAST:event_cmbDrzavaActionPerformed

    private void cmbKlubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKlubActionPerformed
 if(cmbKlub.getSelectedIndex() == -1) return;

    try {

        String klub = cmbKlub.getSelectedItem().toString();

        Connection conn = DBConnection.connect();

        String sql =
        "SELECT klub.Sajt, klub.Amblem, stadion.Naziv, stadion.Adresa " +
        "FROM klub " +
        "INNER JOIN stadion ON klub.StadionID = stadion.StadionID " +
        "WHERE klub.NazivKluba = ?";

        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, klub);

        ResultSet rs = ps.executeQuery();

        if(rs.next()) {

            lblGrad.setText(rs.getString("Adresa"));

            lblStadion.setText(rs.getString("Naziv"));

            lblSajt.setText(rs.getString("Sajt"));

        String amblem = rs.getString("Amblem");
ImageIcon icon = new ImageIcon("slike/" + amblem);

Image img = icon.getImage();
Image novaSlika = img.getScaledInstance(55, 80, java.awt.Image.SCALE_SMOOTH);

lblSlika.setIcon(new ImageIcon(novaSlika)); 


        }
    } catch(Exception e) {
        System.out.println(e);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKlubActionPerformed

    private void btnIzlazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzlazActionPerformed
          System.exit(0);
    }//GEN-LAST:event_btnIzlazActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        loadDrzave();

if(cmbDrzava.getItemCount() > 1) {
    cmbDrzava.setSelectedIndex(0);
}
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziActionPerformed
       try {

           if(dcDatum.getDate() == null) {
    javax.swing.JOptionPane.showMessageDialog(
        this,
        "Izaberite datum!"
    );
    return;
}
    SimpleDateFormat sdf =
            new SimpleDateFormat("yyyy-MM-dd");
   
    String datum =
            sdf.format(dcDatum.getDate());
    System.out.println(datum);

    Connection conn = DBConnection.connect();

    String sql =

"SELECT s.Naziv, " +
"k1.NazivKluba AS Domacin, " +
"u.Rezultat, " +
"k2.NazivKluba AS Gost " +
"FROM utakmica u " +
"INNER JOIN klub k1 ON u.DomacinID = k1.KlubID " +
"INNER JOIN klub k2 ON u.GostID = k2.KlubID " +
"INNER JOIN stadion s ON k1.StadionID = s.StadionID " +
"WHERE u.Datum = '" + datum + "'";

    PreparedStatement ps =
            conn.prepareStatement(sql);

System.out.println(
    new java.sql.Date(dcDatum.getDate().getTime())
);

    ResultSet rs = ps.executeQuery();

    DefaultTableModel model =
        (DefaultTableModel) tblRezultati.getModel();

    model.setRowCount(0);

System.out.println(sql);


model.setRowCount(0);

int brojac = 0;

while(rs.next()) {

    brojac++;

    String[] rezultat =
        rs.getString("Rezultat").split(":");

    model.addRow(new Object[] {

        rs.getString("Naziv"),
        rs.getString("Domacin"),
        rezultat[0],
        rezultat[1],
        rs.getString("Gost")

    });

}

System.out.println("Broj utakmica: " + brojac);

} catch(Exception e) {

    System.out.println(e);

}
    }//GEN-LAST:event_btnPrikaziActionPerformed

    private void btnIzlaz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzlaz2ActionPerformed
         System.exit(0);
    }//GEN-LAST:event_btnIzlaz2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GlavnaForma().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PodaciKluba;
    private javax.swing.JButton btnIzlaz;
    private javax.swing.JButton btnIzlaz2;
    private javax.swing.JButton btnPrikazi;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cmbDrzava;
    private javax.swing.JComboBox<String> cmbGrad;
    private javax.swing.JComboBox<String> cmbKlub;
    private com.toedter.calendar.JDateChooser dcDatum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblGrad;
    private javax.swing.JLabel lblSajt;
    private javax.swing.JLabel lblSlika;
    private javax.swing.JLabel lblStadion;
    private javax.swing.JTable tblRezultati;
    // End of variables declaration//GEN-END:variables
}
